all:
	make -C fsfuzzer all
	make -C linux all
	make -C ltp all
	make -C randmod all
	make -C scrashme all

clean:
	make -C fsfuzzer clean
	make -C linux clean
	make -C ltp clean
	make -C randmod clean
	make -C scrashme clean

distclean:
	make -C fsfuzzer distclean
	make -C linux distclean
	make -C ltp distclean
	make -C randmod distclean
	make -C scrashme distclean
